### ISSUE TITLE
USER STORY: Authentication-Sign in to the app

### ISSUE THREAD

**Issue by AlaYousef** [AlaYousef/Cooking-pp5#10]
EPIC: Authentication

USER STORY: Sign in: As a **user** I can **sign in to the app** so that **I can access functionality for logged in users**

**Acceptance Criteria**
- Sign in link should be clickable and visible in the navbar
- Users should be navigate to the sign in form on clicking the link
- Users should be able to input reuired information and click sign in button to sign in

**Tasks**
- [ ] Create sign in form 
- [ ] Implement handle events and handle errors functions.
- [ ] Access and refresh tokens
