### ISSUE TITLE
USER STORY: Authentication - Refreshing access tokens

### ISSUE THREAD

**Issue by AlaYousef** [AlaYousef/Cooking-pp5#12]
EPIC: Authentication

USER STORY: As a **user** I can **maintain my logged-in status until I choose to log out** so that **my user experience is not compromised**

**Acceptance Criteria**
- Users should be able logged in for longer.

**Tasks**
- [ ] Initiate axios interceptors.
- [ ] Use and import useMemo hook
- [ ] Implement handleMount function
