### ISSUE TITLE
USER STORY: Authentication-Create new account

### ISSUE THREAD

**Issue by AlaYousef** [AlaYousef/Cooking-pp5#9]
EPIC: Authentication

USER STORY: As a **user** I can **create a new account** so that **I can access all the features for signed up users**

**Acceptance Criteria**
- Sign up link should be clickable and visible  in the navbar.
- After click on the link, users should be navigate to the sign up form
- User should input a valid information and click sign up button

**Tasks**
- [ ] Create sign up form.
- [ ] implement handle events and errors functions.
- [ ] Redirect to the sign in page after input the required information.
